var nom = "niang";
var prenom = " mo";
var age = 25;
var or = "fu bitch";
console.log(or);
or = true;
console.log(or);
var faux = false;
console.log(faux);
console.log("i'm" + prenom + "\t" + nom + "\ti'm" + age);
